# Module 1: Functional Programming part 2 (Homework)
Course: Advanced Programming for CSAI (Spring 2026)

Topics covered in this module:
- Iterables, Iterators and Generators. 
- Lazy Computation. 

You are advised to work on this notebook after, or in parallel to, consulting other materials of the module, such as the slide deck and book chapters. The notebook contains examples and exercises that should help you understand and apply the concepts introduced in the rest of materials. You may also use the official Python docs: https://docs.python.org/3/.

Do not hesitate to be creative when trying out the examples: you can play with the code. You can try variants of the examples and exercises, print values of the variables to understand what is going on at every step, and come up with different solutions to the same exercise and think about relative advantages of each one.

---

## Iterables, Iterators and Generators

#### HW 1: 
Let's create a list comprehension which creats a new list of capitalised color names (from myList)

In [ ]:
# Lists are iterable objects:
myList = ['blue', 'red', 'yellow']

# Your solution to HW-1 goes here:

##################################

print(myBigList)

['BLUE', 'RED', 'YELLOW']


Now, let's embed this in one statement; no **for** just a list comprehension

In [ ]:
# Your solution to HW-1 goes here:

##################################

BLUE
RED
YELLOW


But this directly prints it. So, how should we assign it to a function which we can call later.

#### HW 1.2, HW 1.3 and HW 1.4: 
Assign the list comprehension to a function and call it toget the print out. Try with and without using a lambda function. Try also with map!

In [ ]:
# Let's create a function which implements a list comprehension which we can call later:
# Your solution to HW-1.2 goes here:


print(make_uppercase(myList))

# or, using lambda functions:
# Your solution to HW-1.3 goes here:

print(make_uppercase_lambda(myList))

# or even using map;
# Your solution to HW-1.4 goes here:

#############################

['BLUE', 'RED', 'YELLOW']
['BLUE', 'RED', 'YELLOW']


Yes, in the above case we need another function so that we don't use a global variable

---

Recall that iterables are collections of items, while iterators are not collections: they are objects that store a state (normally, an index). When looping over an iterable, the iterator of that iterable will tell us which item of the collection is the next to be read.

As in class, imagine you have a list with 10 strings. Your list is an iterable, and therefore it has an `__iter__` method. We can print the contents of the list without using the `__iter__ `method; however, if we want to loop over the list (for example with a **for** loop), then Python will implicitly call the `__iter__` method to obtain an interator for the list. The iterator will keep track of which item should be read next by the **for** loop.  Therefore, the iterator will have a state, and a `__next__`method that will inform the **for** loop of which item in the list should be read in the current iteration.


#### HW-2:

Now that you know which objects have a `__next__` method, 
Now, create a small function that obtains an iterator from myList (i.e., iter(myList)) 
and manually calls next(...) three times, storing the items in a list named `result_list` and then print `result_list` at the end.



In [ ]:
## Your solution to HW-2 goes here:

###########################

print(first_three(myList))   # => ['blue', 'red', 'yellow']  (depending on the content of myList)
# - You should see the first three items of myList printed, e.g. ['blue', 'red', 'yellow'] 
# (if myList has at least 3 elements).


['blue', 'red', 'yellow']


Note that the iterator provides us with the __ next __  method, which was not available in the iterable!

Note also that the __ iter __ method is not listed above: this is a method that is common both to iterables and iterators (in the case of an iterator, __ iter __ returns self: this is just a language design feature that makes the implementation simpler behind the curtains).

### HW-3: 

If you look at the methods listed above, you can see that the the iterable has a method `__ len __` . This is the method called when we do len(myList) to obtain the number of elements in the list. Note that this method is not available in the iterator: you can further verify that len(myIterator) raises a TypeError.

Now look at the example below. The function **firstn** is a generator, as it uses **yield**. As you can see, the generator has an `__ iter __` method, and also a `__ next __` method: 

In [10]:
# This function is a generator:
def firstn(n):
    num = 0
    while num < n:
        yield num
        num += 1

g = firstn(4)
print("Generator object:", g)
print("iter in generator:", hasattr(g, '__iter__'))
print("next in generator:", hasattr(g, '__next__'))


Generator object: <generator object firstn at 0x7f9ebe5a0d00>
iter in generator: True
next in generator: True


Given what you have seen above, and what you know of generators, and according to what we talked in class, it should be clear that *g* does not have a `__len__` method.

In [14]:
hasattr(g, '__len__')

False

#### HW-3.1:
Create a generator function `squares(n)` that yields the squares of 
numbers from 0 up to `n` (inclusive). 
Then obtain an instance `gen = squares(5)` 
and manually print `next(gen)` several times. 


In [ ]:
## Your solution to HW-4.1 goes here:



###########################

gen = squares(5)
print(next(gen))  # => 0
print(next(gen))  # => 1
print(next(gen))  # => 4
# ......
# .....
# Printing next(gen) repeatedly should show 0, 1, 4, 9, 16, 25.


0
1
4


#### HW-4.1:

Consider a generator function `gen_random_floats(n)` that yields `n` random float values. 
 
 **Hint:** `random` package is alredy imported. You can use the `random.random()` function to generate random numbers.
 
1) Implement the `gen_random_floats(n)` generator 
2) Call `gen_random_floats(n)` with `n = 5` to create a generator and store it in the variable `rand_5_nums`.
3) In a for loop collect the results of the `rand_5_nums` and store them in the `rand_gen_list`.
4) Print the length of `rand_gen_list` to confirm it is `n`.


In [ ]:
import random

## Your solution to FA-6 goes here:


##############################

print(len(rand_gen_list)) # => 5
print(rand_gen_list)
# If n = 5, you should see 5 random floats in rand_gen_list, 
# e.g., [0.43, 0.89, 0.01, 0.47, 0.99], and len(rand_gen_list) = 5

5
[0.82, 0.29, 0.21, 0.73, 0.44]


#### FA-4.2:
 
What would happen if you directly cast `rand_5_nums` to a list by calling `list()`? 

Make a `rand_gen_list2` this time by using `list()` and then print the length of `rand_gen_list2` to confirm it is `n`. (Pay closer attention to naming the variables we are printing `rand_gen_list2` here and not `rand_gen_list`)

In [ ]:
## Your solution to FA-6-a goes here:

###########################

print(len(rand_gen_list2)) # => 5
print(rand_gen_list2)
# If n = 5, you should see 5 random floats in fa6a_list, 
# e.g., [0.43, 0.89, 0.01, 0.47, 0.99], and len(fa6a_list) = 5

0
[]


----
## Lazy evaluation


When working on the previous section, you should have noticed some differences in the behavior of generators, compared to other iterables such as lists and dictionaries. This has to do with the fact that generators are lazy. 

When you run the examples, note that Python uses lazy evaluation for Boolean expressions with **and** and **or**. 

As you know, generators are also lazy in Python: they don't create all the results immediately, but delay their evaluation until the moment they are needed. This applies both to generator expressions and generator functions with *yield*. 


In [26]:
# The numbers generator defined below has an infinite loop (while True)!
def numbers(): 
    i = 0
    while True:     
        yield i 
        i += 1
               
# However, we can call this function without running into an infinite loop!
# This is thanks to lazy evaluation: the numbers of this generator are only computed when needed.
g = numbers()

# We can get the next number as many times as we want 
print(next(g))
print(next(g))
print(next(g))

for _ in range(5):
    print(next(g))

print('')

# But don't do the following! (unless you add a break condition)
# for number in g:
#    print(number)
# Since there is no stopping condition, this loop would run infinitely 
# (and you'd have to stop it on time and possibly restart the kernel, and perhaps even your computer)

# The itertools module provides a generator with the same functionality as numbers:
import itertools 

g = itertools.count()
print(next(g))
print(next(g))
print(next(g))


0
1
2
3
4
5
6
7

0
1
2


Here is the example (from the in-class notebook) that uses the numbers generator. Note that it uses a break condition!

In [27]:
def sum_to(n):
    sum = 0
    for i in numbers():
        if i == n: 
            break
        sum += i
    return sum

print("Result: ", sum_to(5))
print("Result: ", sum_to(15))
print("Result: ", sum_to(30))


Result:  10
Result:  105
Result:  435


Here we repead the example from class. We have some *data* stored in a list, and a function that always accesses it in insertion order, up to a certain position (included), and returns the last accessed element.


In [28]:
data = [2,53, 1, 6674, 23, 16435, 95, 220, 32, 27, 3, 96, 261, 2856]

l = [x for x in data if x % 2 == 0]

g = (x for x in data if x % 2 == 0)

print(l)
print(g)

def access_in_order(it, until, verbose=False):
    for i, element in enumerate(it):
        if verbose:
            print("Accessing element ", i, ": ", element)
        if i >= until:
            return element
    
    
print(access_in_order(l, 2, True))
print(access_in_order(g, 2, True))   
print(access_in_order(g, 2, True))   # Note that we get a different result now! 
                                     # since g is a generator, it keeps the state
g = (x for x in data if x % 2 == 0)  # We need to create it again if we want to regenerate it
print(access_in_order(g, 2, True))


[2, 6674, 220, 32, 96, 2856]
<generator object <genexpr> at 0x7f9ebe4d5700>
Accessing element  0 :  2
Accessing element  1 :  6674
Accessing element  2 :  220
220
Accessing element  0 :  2
Accessing element  1 :  6674
Accessing element  2 :  220
220
Accessing element  0 :  32
Accessing element  1 :  96
Accessing element  2 :  2856
2856
Accessing element  0 :  2
Accessing element  1 :  6674
Accessing element  2 :  220
220


#### HW-5:

Rewrite the function `access_in_order()` as a generator function called `yield_in_order`, 
which yields each element up to `until` index, instead of returning a single element.

Implementation steps:
1) `yield_in_order(it, until)` should yield each item from `it` until `i >= until`.
2)  Demonstrate by converting its output to a list or manually using `next()`.

**Hint:** If we do `list(yield_in_order(l, 2))` for `l=[2, 6674, 220, ...]`, it should produce the first 3 elements from `l` (indices 0,1,2).




In [ ]:
## Your solution to HW-5 goes here:
   


###########################

result_list = list(yield_in_order(l, 2))
print(result_list)      # => [2, 6674, 220]  (according to the data we had defined)

[2, 6674, 220]


# References

* Notebook adapted from Fred Blain's 2025 edition.